### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by c1a1o1** [AlamiMejjati/plop#1]
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
  [TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
  [TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
  [TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
  [TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
  [TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
  [TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
  [TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
  [TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
Model/g_A_ae/c1/Conv/weights:0
Model/g_A_ae/c1/Conv/biases:0

**Comment by AlamiMejjati** [comment]
Could you explain further what is your training error? 
''''''
[TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
[TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
[TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
[TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
[TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
[TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
[TL] UpSampling2dLayer up1: is_scale:False size:[128, 128] method:1 align_corners:False
[TL] UpSampling2dLayer up2: is_scale:False size:[256, 256] method:1 align_corners:False
Model/g_A_ae/c1/Conv/weights:0
Model/g_A_ae/c1/Conv/biases:0
''''''

As the lines bellow are from explicit prints in the script describing operations and model variables.
