### ISSUE TITLE
Training on GPU is taking a lot of RAM

### ISSUE THREAD

**Issue by viniciusarruda** [AlamiMejjati/plop#4]
I'm training on a GPU but it's taking a lot of RAM (I have 24 GB and it's consuming ~22GB). Is this expected ? What can I do to reduce this amount of RAM consumption ?

**Comment by AlamiMejjati** [comment]
Hello vinicius, I have the same memory consumption as you (around 22GB). I am not sure yet why the amount of RAM required is that high but I will get back to you when I figure it out. Meanwhile maybe you can try reducing the number of residual blocks from the generators.
