### ISSUE TITLE
 the test is no results.

### ISSUE THREAD

**Issue by caogule** [AlamiMejjati/plop#5]
I run the code is 100epoch，I see the the result of 100 epoch is pool. the test  have error ,there is no results when I run  test

**Comment by AlamiMejjati** [comment]
Could you please give more details about the error you receive?

**Comment by caogule** [comment]
When I run the model ，I get“ epoch_99.html”，means run 100 epoch，I see this “epoch_99.html",I find the image is not good.
 
![tim 20180903155524](https://user-images.githubusercontent.com/19268488/45006766-28d71000-b02d-11e8-8097-f085f916e4e1.png)


then, I test this model, 
I run
python main.py --to_train=0 --log_dir=./output/AGGAN/exp_01 --config_filename=./configs/exp_01_test.json --checkpoint_dir=./output/AGGAN/exp_01/20180728-120640 
20180728-120640  is my train result.
this is my test result
I think there is no change

![0 v3 5y 0t d niy1](https://user-images.githubusercontent.com/19268488/45006777-312f4b00-b02d-11e8-8ee4-11c66e633ab6.png)

**Comment by AlamiMejjati** [comment]
Oh I see. I think when creating the csv 'horse2zebra_test.csv' you should inverse the sense of the folders testA and testB. 
In your case, the network is trying to map horse to horse and zebra to zebra which would explain why there are no changes.

**Comment by AlamiMejjati** [comment]
If you use 'test_' instead of 'test' which I think you do, then you should be careful to feed the right domain for G_S and G_T (lines 558, 559 in main.py).

**Comment by caogule** [comment]
I run 
 python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testA" --image_path_b="./input/horse2zebra/testB" --dataset_name="horse2zebra_test" --do_shuffle=0
or
 python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testB" --image_path_b="./input/horse2zebra/testA" --dataset_name="horse2zebra_test" --do_shuffle=0

then 
I run 

python main.py --to_train=0 --log_dir=./output/AGGAN/exp_01 --config_filename=./configs/exp_01_test.json --checkpoint_dir=./output/AGGAN/exp_01/20180728-120640
the result is sample ，and there is no change

**Comment by AlamiMejjati** [comment]
There are two test functions: 'test' and 'test_'. 
In your case you are using 'test_', which means that running: 

python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testA" --image_path_b="./input/horse2zebra/testB" --dataset_name="horse2zebra_test" --do_shuffle=0

or 

python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testB" --image_path_b="./input/horse2zebra/testA" --dataset_name="horse2zebra_test" --do_shuffle=0

Will **NOT** make any change as 'test_' does not use the 'horse2zebra_test.csv' file. 

You have two solutions: 

1- You can change `cyclegan_model.test_()' to `cyclegan_model.test()' in line 680 in 'main.py' then test with one of the 'horse2zebra_test.csv' using one of the two configurations you already created.

**or**

2- You can leave `cyclegan_model.test_()' unchanged and modify lines 560 and 562 in 'main.py' by changing line 560 from 
filenamesA = glob.glob(os.path.join('./input', 'horse2zebra', foldB, '*.jpg'))
to 
filenamesA = glob.glob(os.path.join('./input', 'horse2zebra', foldA, '*.jpg'))

and line 562 from 
filenamesB = glob.glob(os.path.join('./input', 'horse2zebra', foldA, '*.jpg'))
to 
filenamesB = glob.glob(os.path.join('./input', 'horse2zebra', foldB, '*.jpg'))

I hope this will be able to help you.

**Comment by caogule** [comment]
thanks you for your help
 in my opinion，I think the result is not good ，maybe horze to zebra  is good，but horse to zebra is not
good

**Comment by viniciusarruda** [comment]
What is the difference between the functions `test_()` and `test()` in main.py ? Thank you.

**Comment by prash-p** [comment]
> There are two test functions: 'test' and 'test_'.
> In your case you are using 'test_', which means that running:
> 
> python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testA" --image_path_b="./input/horse2zebra/testB" --dataset_name="horse2zebra_test" --do_shuffle=0
> 
> or
> 
> python -m create_cyclegan_dataset --image_path_a="./input/horse2zebra/testB" --image_path_b="./input/horse2zebra/testA" --dataset_name="horse2zebra_test" --do_shuffle=0
> 
> Will **NOT** make any change as 'test_' does not use the 'horse2zebra_test.csv' file.
> 
> You have two solutions:
> 
> 1- You can change `cyclegan_model.test_()' to `cyclegan_model.test()' in line 680 in 'main.py' then test with one of the 'horse2zebra_test.csv' using one of the two configurations you already created.
> 
> **or**
> 
> 2- You can leave `cyclegan_model.test_()' unchanged and modify lines 560 and 562 in 'main.py' by changing line 560 from
> filenamesA = glob.glob(os.path.join('./input', 'horse2zebra', foldB, '_.jpg')) to filenamesA = glob.glob(os.path.join('./input', 'horse2zebra', foldA, '_.jpg'))
> 
> and line 562 from
> filenamesB = glob.glob(os.path.join('./input', 'horse2zebra', foldA, '_.jpg')) to filenamesB = glob.glob(os.path.join('./input', 'horse2zebra', foldB, '_.jpg'))
> 
> I hope this will be able to help you.

What is the purpose of the two test functions 'test()' and 'test_()'? It seems like test_() is using a hardcoded path to the horse2zebra dataset?

**Comment by zychen2016** [comment]
Hello,do you get results use pre_trained model?

**Comment by prash-p** [comment]
I haven't tried using pre-trained models, but I get results when I train my own model.
