### ISSUE TITLE
About attention model

### ISSUE THREAD

**Issue by nile649** [AlamiMejjati/plop#6]
Hi, could you explain your attention model more in detail?

**Comment by AlamiMejjati** [comment]
Hi Nilesh, please refer to our paper https://arxiv.org/pdf/1806.02311.pdf for detailed explanations.

**Comment by nile649** [comment]
Hi, I did read the paper, but I wish to just train the attention network. I tried to implement the attention network only, and it seems not giving better segmentation.

**Comment by AlamiMejjati** [comment]
Our attention network is an autoencoder formed by a series of convolutions followed by a residual block then a series of upsampling+convolutions are performed to obtain a continuous mask.
